//nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: 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

npmScopes:
  jaclight:
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"

//yarnPath: .yarn/releases/yarn-4.0.2.cjs
